Added ctags support

diff --git a/install b/install
--- a/install
+++ b/install
@@ -37,6 +37,12 @@ if [ $? -ne 0 ]; then
   brew install exa || exit 1
 fi
 
+ctags --version 2>&1 | grep Universal 2>&1 >/dev/null
+if [ $? -ne 0 ]; then
+  echo "universal-ctags not found, installing via brew"
+  brew install --HEAD universal-ctags/universal-ctags/universal-ctags || exit 1
+fi
+
 if [ ! -d ~/.config ]; then
   mkdir ~/.config
 fi
