Added fzf search to base install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -43,6 +43,13 @@ if [ $? -ne 0 ]; then
   brew install exa || exit 1
 fi
 
+which fzf 2>&1 >/dev/null
+if [ $? -ne 0 ]; then
+  echo "fzf not found, installing via brew"
+  brew install fzf || exit 1
+  $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish || exit 1
+fi
+
 ctags --version 2>&1 | grep Universal 2>&1 >/dev/null
 if [ $? -ne 0 ]; then
   echo "universal-ctags not found, installing via brew"
