Fixed initial install for empty systems

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,9 +17,9 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-which python3 2>&1 >/dev/null
+which python3 2>&1 | grep "/usr/local/bin/" 2>&1 >/dev/null
 if [ $? -ne 0 ]; then
-  echo "Python 3 not found, installing via brew"
+  echo "Python 3 not found or not new enough, installing via brew"
   brew install python3 || exit 1
 fi
 
@@ -54,6 +54,12 @@ which trash 2>&1 >/dev/null
 if [ $? -ne 0 ]; then
   echo "trash not found, installing via brew"
   brew install trash || exit 1
+fi
+
+which direnv 2>&1 >/dev/null
+if [ $? -ne 0 ]; then
+  echo "direnv not found, installing via brew"
+  brew install direnv || exit 1
 fi
 
 ctags --version 2>&1 | grep Universal 2>&1 >/dev/null
