feat: mise as standard version control

diff --git a/install b/install
--- a/install
+++ b/install
@@ -68,10 +68,10 @@ if [ $? -ne 0 ]; then
   brew install direnv || exit 1
 fi
 
-which rtx 2>&1 >/dev/null
+which mise 2>&1 >/dev/null
 if [ $? -ne 0 ]; then
-  echo "rtx not found, installing via brew"
-  brew install rtx || exit 1
+  echo "mise not found, installing via brew"
+  brew install mise || exit 1
 fi
 
 which just 2>&1 >/dev/null
